/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 exhibition.gltf --debug 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/exhibition.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SM_Plane.geometry} material={nodes.SM_Plane.material} />
      <mesh geometry={nodes.SM_Character.geometry} material={nodes.SM_Character.material} />
      <mesh geometry={nodes.SM_DoorL.geometry} material={nodes.SM_DoorL.material} />
      <mesh geometry={nodes.SM_HandleL.geometry} material={nodes.SM_HandleL.material} />
      <mesh geometry={nodes.DoorL.geometry} material={nodes.DoorL.material} />
      <mesh geometry={nodes.SM_HandleR.geometry} material={nodes.SM_HandleR.material} />
      <mesh geometry={nodes.SM_DoorR.geometry} material={nodes.SM_DoorR.material} />
      <mesh geometry={nodes.DoorR.geometry} material={nodes.DoorR.material} />
      <mesh geometry={nodes.SM_Mainframe.geometry} material={nodes.SM_Mainframe.material} />
      <mesh geometry={nodes.SM_Interlock.geometry} material={nodes.SM_Interlock.material} />
      <mesh geometry={nodes.SM_Windows.geometry} material={nodes.SM_Windows.material} />
      <mesh geometry={nodes.SM_Floor.geometry} material={nodes.SM_Floor.material} />
      <mesh geometry={nodes.SM_Grass.geometry} material={nodes.SM_Grass.material} />
      <mesh geometry={nodes.SM_Portic11.geometry} material={nodes.SM_Portic11.material} />
      <mesh geometry={nodes.SM_Portic10.geometry} material={nodes.SM_Portic10.material} />
      <mesh geometry={nodes.SM_Portic09.geometry} material={nodes.SM_Portic09.material} />
      <mesh geometry={nodes.SM_Portic05.geometry} material={nodes.SM_Portic05.material} />
      <mesh geometry={nodes.SM_Portic06.geometry} material={nodes.SM_Portic06.material} />
      <mesh geometry={nodes.SM_Portic02.geometry} material={nodes.SM_Portic02.material} />
      <mesh geometry={nodes.SM_Portic01.geometry} material={nodes.SM_Portic01.material} />
      <mesh geometry={nodes.SM_Portic03.geometry} material={nodes.SM_Portic03.material} />
      <mesh geometry={nodes.SM_Portic04.geometry} material={nodes.SM_Portic04.material} />
      <mesh geometry={nodes.SM_Roof.geometry} material={nodes.SM_Roof.material} />
      <mesh geometry={nodes.SM_Portic12.geometry} material={nodes.SM_Portic12.material} />
      <mesh geometry={nodes.SM_Portic08.geometry} material={nodes.SM_Portic08.material} />
      <mesh geometry={nodes.SM_Portic07.geometry} material={nodes.SM_Portic07.material} />
      <mesh geometry={nodes.SM_InternalFrame.geometry} material={nodes.SM_InternalFrame.material} />
      <mesh geometry={nodes.SM_Column035.geometry} material={nodes.SM_Column035.material} />
    </group>
  )
}

useGLTF.preload('/exhibition.gltf')
